### ISSUE TITLE
how to customer docker image

### ISSUE THREAD

**Issue by minikiller** [dhirajsb/camel-hello-world#3]
Dear Sir:
    I forked fabric8io-images/s2i project and build my image as karaf-sti, then I use your os3-app-template.json template file and change field to "dockerImageRepository": "172.30.124.220:5000/karaf/s2i-karaf" . But when i create a new app from this template, it is not auto to build .  I do not know why.
    Another question is what is different between fuse-sti and karaf4-sti ? And fabric8io-images/s2i. I only want to use it to build my project to run under openshift origin. which one is prefer?

**Comment by dhirajsb** [comment]
This is a personal project I had created from archetypes at https://github.com/fabric8io/ipaas-quickstarts. It is now outdated and is not supported. Please use the ipaas-quickstarts project and it's archetypes to create your own Camel on OpenShift project. Better yet, take a look at https://github.com/fabric8io/fabric8/ at it's CI/CD pipeline to easily create Camel microservices on OpenShift.

**Comment by minikiller** [comment]
Thanks for your reply! I use karaf as OSGI container, so I fork this project and use it for S2i build on OpenShift. Would you like to give some links about how to use karaf under fabric8, thanks.
